### ISSUE TITLE
add redux

### ISSUE THREAD

**Issue by nsfmc** [studiosnack/brews-clues#8]
everyone uses redux right now, it's just _de rigeur_, so i had assumed we would use it, but i want to make sure we agree that it's a good idea. The alternative is `setState` _until_ we decide we need redux, but because we already have a sort of data model, it makes sense to use redux from the outset _even though it will feel weighty at first._

if you use chrome, you should install the [redux devtools chrome extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) because it will make it easy to see what's going on.

also, if you haven't installed React [Devtools Extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) for chrome, you should totally do that as well. those two make both react and redux more of a treat to work with.

**Comment by chiaberry** [comment]
Done and Done --
